import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Globe, Trash2, Download, Calendar, Search } from 'lucide-react';
import { Card } from '../../ui/Card';
import { Button } from '../../ui/Button';
import { Input } from '../../ui/Input';
import { useAuth } from '../../hooks/useAuth';
import { useNavigate } from 'react-router-dom';
import { supabase } from '../../../backend/lib/supabase';
import { TreeBackground } from '../../ui/TreeBackground';
import { toast } from 'react-hot-toast';

interface Translation {
  id: string;
  source_language_code: string;
  target_language_code: string;
  source_text: string;
  translated_text: string;
  confidence_score: number;
  created_at: string;
  translation_type: string;
  character_count: number;
  processing_time_ms: number;
}

export function HistoryPage() {
  const { user, loading: authLoading } = useAuth();
  const navigate = useNavigate();
  const [translations, setTranslations] = useState<Translation[]>([]);
  const [filteredTranslations, setFilteredTranslations] = useState<Translation[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');
  const [filterType, setFilterType] = useState<'all' | 'text' | 'audio' | 'document'>('all');
  const [sortBy, setSortBy] = useState<'date' | 'confidence'>('date');

  useEffect(() => {
    if (!authLoading) {
      if (!user) {
        navigate('/auth');
        return;
      }
      fetchTranslations();
    }
  }, [user, authLoading, navigate]);

  useEffect(() => {
    filterAndSortTranslations();
  }, [translations, searchQuery, filterType, sortBy]);

  const fetchTranslations = async () => {
    if (!user) return;

    try {
      const { data, error } = await supabase
        .from('translations')
        .select('*')
        .eq('user_id', user.id)
        .order('created_at', { ascending: false });

      if (error) throw error;
      setTranslations(data || []);
    } catch (error) {
      toast.error('Failed to load translation history');
    } finally {
      setLoading(false);
    }
  };

  const filterAndSortTranslations = () => {
    let filtered = [...translations];

    if (searchQuery.trim()) {
      filtered = filtered.filter(t =>
        t.source_text.toLowerCase().includes(searchQuery.toLowerCase()) ||
        t.translated_text.toLowerCase().includes(searchQuery.toLowerCase())
      );
    }

    if (filterType !== 'all') {
      filtered = filtered.filter(t => t.translation_type === filterType);
    }

    if (sortBy === 'confidence') {
      filtered.sort((a, b) => (b.confidence_score || 0) - (a.confidence_score || 0));
    }

    setFilteredTranslations(filtered);
  };

  const handleDelete = async (translationId: string) => {
    if (!confirm('Are you sure you want to delete this translation?')) return;

    try {
      const { error } = await supabase
        .from('translations')
        .delete()
        .eq('id', translationId)
        .eq('user_id', user?.id);

      if (error) throw error;

      setTranslations(translations.filter(t => t.id !== translationId));
      toast.success('Translation deleted successfully');
    } catch (error) {
      toast.error('Failed to delete translation');
    }
  };

  const handleDownload = (translation: Translation) => {
    const content = `Translation Report
===================

Date: ${new Date(translation.created_at).toLocaleString()}
From: ${getLanguageName(translation.source_language_code)}
To: ${getLanguageName(translation.target_language_code)}
Type: ${translation.translation_type}
Confidence: ${Math.round((translation.confidence_score || 0) * 100)}%

Original Text:
${translation.source_text}

Translated Text:
${translation.translated_text}

---
Generated by TribalBridge
`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `translation-${translation.id}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast.success('Translation downloaded');
  };

  const getLanguageName = (code: string) => {
    const languageNames: { [key: string]: string } = {
      'gon': 'Gondi', 'sat': 'Santali', 'ho': 'Ho', 'brx': 'Bodo',
      'en': 'English', 'hi': 'Hindi', 'bn': 'Bengali', 'es': 'Spanish',
      'fr': 'French', 'de': 'German', 'pt': 'Portuguese', 'zh': 'Chinese',
      'ja': 'Japanese', 'ar': 'Arabic', 'nav': 'Navajo', 'che': 'Cherokee'
    };
    return languageNames[code] || code.toUpperCase();
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  if (loading) {
    return (
      <TreeBackground variant="minimal">
        <div className="min-h-screen flex items-center justify-center">
          <div className="animate-spin h-8 w-8 border-2 border-primary-600 border-t-transparent rounded-full"></div>
        </div>
      </TreeBackground>
    );
  }

  return (
    <TreeBackground variant="minimal">
      <div className="min-h-screen py-8">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            className="mb-8"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
          >
            <h1 className="text-3xl font-display font-bold text-gray-900 mb-2">
              Translation History
            </h1>
            <p className="text-gray-600">
              View, search, and manage your translation history
            </p>
          </motion.div>

          <motion.div
            className="mb-6"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
          >
            <Card>
              <div className="flex flex-col md:flex-row gap-4">
                <div className="flex-1">
                  <div className="relative">
                    <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" size={20} />
                    <Input
                      type="text"
                      placeholder="Search translations..."
                      value={searchQuery}
                      onChange={(e) => setSearchQuery(e.target.value)}
                      className="pl-10"
                    />
                  </div>
                </div>
                
                <div className="flex gap-2">
                  <select
                    value={filterType}
                    onChange={(e) => setFilterType(e.target.value as any)}
                    className="px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"
                  >
                    <option value="all">All Types</option>
                    <option value="text">Text</option>
                    <option value="audio">Audio</option>
                    <option value="document">Document</option>
                  </select>

                  <select
                    value={sortBy}
                    onChange={(e) => setSortBy(e.target.value as any)}
                    className="px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"
                  >
                    <option value="date">Sort by Date</option>
                    <option value="confidence">Sort by Confidence</option>
                  </select>
                </div>
              </div>

              <div className="mt-4 flex items-center justify-between text-sm text-gray-600">
                <span>
                  Showing {filteredTranslations.length} of {translations.length} translations
                </span>
              </div>
            </Card>
          </motion.div>

          <motion.div
            className="space-y-4"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
          >
            {filteredTranslations.length > 0 ? (
              filteredTranslations.map((translation, index) => (
                <motion.div
                  key={translation.id}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: index * 0.05 }}
                >
                  <Card hover>
                    <div className="flex items-start justify-between gap-4">
                      <div className="flex-1">
                        <div className="flex items-center gap-3 mb-3">
                          <span className="text-sm font-medium text-gray-900">
                            {getLanguageName(translation.source_language_code)}
                          </span>
                          <span className="text-gray-400">→</span>
                          <span className="text-sm font-medium text-gray-900">
                            {getLanguageName(translation.target_language_code)}
                          </span>
                          <span className="px-2 py-1 bg-green-100 text-green-700 text-xs rounded-full">
                            {Math.round((translation.confidence_score || 0) * 100)}% confidence
                          </span>
                          <span className="px-2 py-1 bg-blue-100 text-blue-700 text-xs rounded-full capitalize">
                            {translation.translation_type}
                          </span>
                        </div>

                        <div className="grid md:grid-cols-2 gap-4 mb-3">
                          <div>
                            <p className="text-xs text-gray-500 mb-1">Original</p>
                            <p className="text-sm text-gray-900">{translation.source_text}</p>
                          </div>
                          <div>
                            <p className="text-xs text-gray-500 mb-1">Translation</p>
                            <p className="text-sm text-gray-900">{translation.translated_text}</p>
                          </div>
                        </div>

                        <div className="flex items-center gap-4 text-xs text-gray-500">
                          <span className="flex items-center gap-1">
                            <Calendar size={14} />
                            {formatDate(translation.created_at)}
                          </span>
                          {translation.processing_time_ms && (
                            <span>{translation.processing_time_ms}ms</span>
                          )}
                          {translation.character_count && (
                            <span>{translation.character_count} characters</span>
                          )}
                        </div>
                      </div>

                      <div className="flex gap-2">
                        <button
                          onClick={() => handleDownload(translation)}
                          className="p-2 text-gray-600 hover:text-primary-600 hover:bg-primary-50 rounded-lg transition-colors"
                          title="Download"
                        >
                          <Download size={18} />
                        </button>
                        <button
                          onClick={() => handleDelete(translation.id)}
                          className="p-2 text-gray-600 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors"
                          title="Delete"
                        >
                          <Trash2 size={18} />
                        </button>
                      </div>
                    </div>
                  </Card>
                </motion.div>
              ))
            ) : (
              <Card>
                <div className="text-center py-12">
                  <Globe className="w-16 h-16 mx-auto mb-4 text-gray-300" />
                  <h3 className="text-lg font-medium text-gray-900 mb-2">
                    {searchQuery || filterType !== 'all' ? 'No translations found' : 'No translation history yet'}
                  </h3>
                  <p className="text-gray-600 mb-6">
                    {searchQuery || filterType !== 'all' 
                      ? 'Try adjusting your search or filters' 
                      : 'Start translating to build your history'}
                  </p>
                  {!searchQuery && filterType === 'all' && (
                    <Button onClick={() => navigate('/translate')} icon={Globe}>
                      Start Translating
                    </Button>
                  )}
                </div>
              </Card>
            )}
          </motion.div>
        </div>
      </div>
    </TreeBackground>
  );
}
